services:
  app:
    build:
      context: .
      # platform: linux/amd64 
    environment:

      # Reading environment variables
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:-""}
      LLM_PROVIDER: ${LLM_PROVIDER:-openrouter}
      PORT: 7860
    ports:
      - "7860:7860"
    volumes:

      # model cache
      - hf_cache:/app/.cache/huggingface

    # for restarts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  hf_cache: {}